Console ui fixes
ONSdigital/sdx-console pull request #121
Opened 2017-12-19 12:50 UTC by dcdarrell9

## What? and Why?
> fix nav tab highlight and removed hardcoded css for banner

## Checklist
  - [ ] CHANGELOG.md updated? (if required)

2017-12-20 08:57 UTC, warrenbailey requested changes

2017-12-20 08:57 UTC, warrenbailey commented on console/templates/partials/navigation_tabs.html
> +        class="navigation-tabs__item navigation-tabs__item--primary">
These blocks look very similar is possible to put the if statement around the bit that actually changes? I.e. the additional class?

2017-12-20 08:57 UTC, warrenbailey commented on console/templates/partials/navigation_tabs.html
> +        class="navigation-tabs__item navigation-tabs__item--primary">
As above

2017-12-20 08:57 UTC, warrenbailey commented on console/templates/partials/navigation_tabs.html
> +        class="navigation-tabs__item navigation-tabs__item--primary">
and here?

2017-12-20 09:04 UTC, dcdarrell9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [sdx-console UI fixes (2)](https://trello.com/c/eDrVTL0o/566-sdx-console-ui-fixes-2)

2017-12-21 10:39 UTC, warrenbailey approved these changes

2017-12-21 10:39 UTC, merged