Feature/heartbeat
ONSdigital/sdx-console pull request #54
Opened 2017-04-24 14:57 UTC by andrewmil

Removed old functionality from console in views.py. Removed .html files. 

Added a basic heartbeat along with unit testing functionality

2017-04-24 16:30 UTC, necrophonic commented on CHANGELOG.md
> +### console 2.0
Just leave these in the "unreleased" block for now - they'll get tagged as 2.0.0 when the release is actually taken.

2017-04-24 16:30 UTC, necrophonic commented on console/settings.py
> +# def get_key(key_name):
If code is not needed anymore just delete it (it's in git anyhow) rather than comment out.

2017-04-24 16:30 UTC, necrophonic commented on console/views.py
> +    logger.info("Heartbeat " + str(heartbeats))
You've got a `structlog` so put the heartbeats into a key/value pair:
```python
logger.info("Heartbeat", heartbeats=heartbeats)
```

Though do we need the actual number of beats? What's the maximum storable int value in `heartbeats` and what would happen on overflow if we just keep counting up (and the service stays up).

Is there a performance/memory implication for the recursive calls?

2017-04-25 09:23 UTC, JamesGardiner requested changes

2017-04-25 09:23 UTC, JamesGardiner commented on CHANGELOG.md
> +### console 2.0
Can we addmove these to unreleased until we cut a tag.

2017-04-25 09:23 UTC, JamesGardiner commented on console/views.py
>  import console.settings as settings
Import order should be PEP8 compliant

2017-04-25 09:23 UTC, JamesGardiner commented on tests/test_console.py
> +from server import app
Import order should be PEP8 compliant

2017-04-25 09:23 UTC, JamesGardiner commented on console/views.py
> +    Timer(30.0, heartbeat, [logger, heartbeats]).start()
Remove the hardcoded delay and use an env var instead.

2017-04-25 09:23 UTC, JamesGardiner commented on test_requirements.txt
>  flake8==2.5.4
Import order should be pep8 compliant

2017-04-25 09:23 UTC, JamesGardiner commented on tests/test_console.py
> +        )
Move this to server.py and implement the class I sent you - this should make graceful shutdown easier in dev/test/prod environments.

2017-04-25 10:53 UTC, andrewmil commented
Using a new method for the heartbeat recommended by James. Client now shuts down after tests run. 

I believe the method in server.py stiff runs recursively. Not sure how this will affect performance but this seems to be a standard solution looking around online

2017-04-25 12:08 UTC, JamesGardiner requested changes

2017-04-25 12:08 UTC, JamesGardiner commented on CHANGELOG.md
Remove space

2017-04-25 12:08 UTC, JamesGardiner commented on README.md
> +| HB_INTERVAL             | '30'                                  | Interval for console heartbeat
Use backticks to keep formatting consistent

2017-04-25 12:08 UTC, JamesGardiner commented on console/settings.py
> +HB_INTERVAL = os.getenv("$HB_INTERVAL", 30)
The $ can be removed

2017-04-25 12:08 UTC, JamesGardiner commented on server.py
> +import console.settings as settings
Can this be `from console import settings`

2017-04-25 12:08 UTC, JamesGardiner commented on server.py
> +    port = int(os.getenv("$PORT", 5000))
Remove $

2017-04-25 14:15 UTC, JamesGardiner approved these changes

2017-04-25 14:18 UTC, merged