Feature/refresh eq surveys
ONSdigital/sdx-console pull request #68
Opened 2017-07-12 12:29 UTC by gemmai95

2017-07-14 09:27 UTC, gemmai95 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) EQ Survey Refresh](https://trello.com/c/X9JTGGuI/162-3-eq-survey-refresh)

2017-07-18 07:55 UTC, warrenbailey requested changes
It's great that you've done this as it's really useful to test with. 👍 

However please could you put the 146* questions at the end of the data block so it retains its sequentially ordering and there's a couple of form types that have additional answers which shouldn't be there.

2017-07-18 07:55 UTC, warrenbailey commented on console/static/surveys/023.0102.json
> +    "22": "705000",
We shouldn't need to add any questions, the refresh should just be the updated comments ie question 146* etc.

2017-07-18 07:55 UTC, warrenbailey commented on console/static/surveys/023.0112.json
> +    "23": "900",
again these aren't needed.

2017-07-18 07:55 UTC, warrenbailey commented on console/static/surveys/023.0203.json
> +    "21": "60000"
Maybe keep the ordering in its original sequential order

2017-07-18 07:55 UTC, warrenbailey commented on console/static/surveys/023.0205.json
> +    "21": "60000",
As above

2017-07-18 11:25 UTC, warrenbailey requested changes
Just a minor one, then it's good to go

2017-07-18 11:25 UTC, warrenbailey commented on console/static/surveys/023.0112.json
> +    "11": "1/4/2016",
11 and 12 are still out of order

2017-07-18 11:25 UTC, warrenbailey commented on console/static/surveys/023.0205.json
> +  "submitted_at": "2016-03-12T10:39:40Z",
Do we need to add submitted_at?

2017-07-18 11:56 UTC, gemmai95 commented on console/static/surveys/023.0205.json
> +  "submitted_at": "2016-03-12T10:39:40Z",
The submitted at appears in all the other json example files. Do we not need this?

2017-07-18 13:53 UTC, warrenbailey approved these changes

2017-07-18 13:53 UTC, warrenbailey commented on console/static/surveys/023.0205.json
> +  "submitted_at": "2016-03-12T10:39:40Z",
It may not make any difference then.

2017-07-19 08:36 UTC, merged