Feature/sdxconsole2 heartbeat to healthcheck
ONSdigital/sdx-console pull request #74
Opened 2017-08-08 12:45 UTC by Malveen

## What? and Why?
> What does this pull request change/fix? Why was it nessessary?
Changed SDX console 2.0 heartbeat feature to health check end point

## Checklist
  - [ ] CHANGELOG.md updated? (if required)

2017-08-08 14:08 UTC, necrophonic commented
Think you have the wrong merge target - this should be targeting the branch `2.0` rather than `master`

2017-08-09 09:22 UTC, Dave-Haynes requested changes

2017-08-09 09:22 UTC, Dave-Haynes commented on server.py
The build fails due to these Flake8 failures:

```
./server.py:2:1: F401 'jsonify' imported but unused
./server.py:16:1: W391 blank line at end of file
```

2017-08-09 09:23 UTC, Malveen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create Health Checkpoint for SDX Console 2.0](https://trello.com/c/Ji1Vw5hI/239-create-health-checkpoint-for-sdx-console-20)

2017-08-09 09:39 UTC, Dave-Haynes approved these changes

2017-08-09 09:42 UTC, merged