Feature/protect reprocess all button
ONSdigital/sdx-console pull request #75
Opened 2017-08-10 09:05 UTC by Malveen

## What? and Why?
> What does this pull request change/fix? Why was it nessessary?
Protected reprocess all button with warning pop up box

## Checklist
  - [ ] CHANGELOG.md updated? (if required)

2017-08-10 09:11 UTC, Malveen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Finish new sdx-console (5)](https://trello.com/c/BRZQChDQ/230-finish-new-sdx-console-5)

2017-08-10 12:47 UTC, JamesGardiner requested changes
LGTM - Just need to update the changelog

2017-08-10 13:19 UTC, Malveen commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1) SDX git repository consistency](https://trello.com/c/OzqUrqJw/235-1-sdx-git-repository-consistency)

2017-08-10 13:44 UTC, tej99 approved these changes

2017-08-11 08:54 UTC, JamesGardiner approved these changes

2017-08-11 09:06 UTC, merged